apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: kafka-examples
build:
  artifacts:
  - image: registry.apos.in/anupam/kafka-examples/kafkasender
    jib:
      project: kafkasender
  - image: registry.apos.in/anupam/kafka-examples/kafkastreams
    jib:
      project: kafkastreams

deploy:
  kubectl:
    manifests:
    - kafkasender/deployment.yaml
    - kafkastreams/deployment.yaml
