apiVersion: v1
kind: Service
metadata:
  name: kafkastreams
  labels:
    app: kafkastreams
spec:
  type: ClusterIP
  selector:
    app: kafkastreams
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9898
    targetPort: 9898
    protocol: TCP
    name: rsock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkastreams
  labels:
    app: kafkastreams
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafkastreams
  template:
    metadata:
      labels:
        app: kafkastreams
    spec:
      containers:
      - name: kafkastreams
        image: registry.apos.in/anupam/kafka-examples/kafkastreams
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: INTERACTIVE_QUERY_HOST
          value: kafkastreams
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9898
          name: rsock
          protocol: TCP
